version: '3.4'

services:
  antgames:
    image: antgames
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3300:3300
